### ISSUE TITLE
The implemetation code

### ISSUE THREAD

**Issue by alimirzaei** [klimzaporojets/DWIE#1]
Hi,
Thank you for releasing this data set.
Have not you released the implementation code of the model? 

Thanks

**Comment by klimzaporojets** [comment]
Hi Ali Mirzaei, 
Thanks for your interest in our work! 

Indeed, the implementation code of the model is not yet released, we are working on cleaning it and will be making it public in coming weeks. 

Best, 

Klim

**Comment by klimzaporojets** [comment]
Hi Ali Mirzaei,

We just updated the README and released the implementation code, please let us know any questions you have. 

Best,

Klim
